### ISSUE TITLE
Unity support? 

### ISSUE THREAD

**Issue by nadir500** [coqui-ai/STT#1795]

**Comment by reuben** [comment]
Can you expand on what your needs are? We have .NET support and are working to add .NET Core support as well soon. Would that be enough?

**Comment by nadir500** [comment]
It would be very helpful to have a TTS running on Unity for voice commands and recognizing words the same way windows speech recognition works. Basically with my case you have an array of words already defined and the voice recognition just works with simple listening to mic functions but it's exclusive to windows machines unfortunately. if there's already .NET support then doing cross platform and being recognized on Unity .NET-4.x/.NET 2.0-Standard would be really great. Unity doesn't natively recognize all libraries and do cross platform when exporting as plugins/packages so it needs to be tested on different platforms first.

**Comment by reuben** [comment]
For TTS you want https://github.com/coqui-ai/TTS, but Unity support will be trickier there as it requires Python to run. I'll ping you in this issue as soon as we have the .NET CI up and running so you can test it and see if it works in Unity.

**Comment by nadir500** [comment]
Much appreciated m8. Also Apologies for the typo, I was referring to STT not TTS.  Looking forward for the outcome of the project.
