### ISSUE TITLE
Per letter and per word confidence score in Metadata output

### ISSUE THREAD

**Issue by reuben** [coqui-ai/STT#1817]

**Comment by zh794390558** [comment]
How to compute per-letter and per-word confidence?

**Comment by reuben** [comment]
This issue is meant to track that work. It needs to be extracted from the PathTrie structure for the returned beams.

**Comment by darlene898** [comment]
> _No description provided._

**Comment by darlene898** [comment]
> _No description provided._

**Comment by reuben** [comment]
Closing in favor of #2021 which has more discussion.
