### ISSUE TITLE
Bug: Node version - npm install, empty index.js in node_modules/stt

### ISSUE THREAD

**Issue by pietrop** [coqui-ai/STT#1830]
**Describe the bug**
In the Node version when installing via `npm install stt` (v `0.10.0-alpha.4`) and running the code example, you get an error 

```
TypeError: Ds.Model is not a constructor
```

But most importantly if you look inside `node_modules/stt/index.js` the file is empty.

**To Reproduce**

1. create a new node project with npm init
2. do `npm install stt`
3. inspect `node_modules/stt/index.js`
3. See error - `index.js` is empty

**Expected behavior**
To be able to install `stt` via npm, import/require the module and use it etc..

**Environment (please complete the following information):**
Mac OS X

**Additional context**
Where's the code that is installed via npm? is it in one of the folders in this repo https://github.com/coqui-ai/STT?

**Comment by reuben** [comment]
We currently only have published pre-built packages for Python on Linux and Python on macOS. We're working as quickly as possible to get other platforms and languages up and running (via porting the CI to GitHub Actions). The empty packaged was pushed to reserve the package name.

**Comment by reuben** [comment]
In the mean time you can still [build it from source](https://stt.readthedocs.io/en/latest/BUILDING.html#install-nodejs-electronjs-bindings).

**Comment by pietrop** [comment]
Thanks, I'll wait for the npm version to be available. And let me know if there's anything I could help with.

**Comment by johanneskropf** [comment]
This is good to know, I already ported my [deepspeech integration for node-red](https://flows.nodered.org/node/node-red-contrib-deepspeech-stt) to [coqui-stt as I will focus on that in the future](https://github.com/johanneskropf/node-red-contribute-coqui-stt) but will wait publishing it till the npm package works.

best regards from Berlin, Johannes

**Comment by reuben** [comment]
I've just published version 0.10.0-alpha.5 of [STT](https://www.npmjs.com/package/stt) and [STT-tflite](https://www.npmjs.com/package/stt-tflite) on npmjs.com. So you should now be able to use the pre-built NodeJS/ElectronJS bindings with a simple `npm install` instead of building from source. Thanks for your patience!

**Comment by johanneskropf** [comment]
Im getting this error when I try to use it:
```
Error: Cannot find module '/home/pi/node-red-contrib-coqui-stt/node_modules/stt/lib/binding/v0.10.0-alpha.5/linux-arm/node-v72/stt.node'
```

**Comment by reuben** [comment]
Yep, coming soon. I should have specified but I didn't realize you were looking for ARM support :)

**Comment by johanneskropf** [comment]
That is good to know as most people using my nodered deepspeech node now I know of do so on one kind of single board computer or another as that is the most popular hardware choice for nodered. So this will be the prerequisite for me to move on to focus on and publish the coqui node for nodered.
Thanks for the continued effort you girls and guys put into the project 👍😀

**Comment by johanneskropf** [comment]
Just to catch up on this is there an eta on the arrival of Linux arm64 or armhf support of the npm binding? I would really like to focus my development on coqui instead of deepspeech but can't as long as it's not available for the majority of my users unfortunately 🙁

**Comment by reuben** [comment]
@johanneskropf hopefully by EOD today :)

**Comment by reuben** [comment]
@johanneskropf I think I got confused somehow. [stt-tflite 0.10.0-alpha.6](https://www.npmjs.com/package/stt-tflite/v/0.10.0-alpha.6) should already have ARMv7 and ARMv8 support in it. Are you sure you were trying `stt-tflite` and not `stt`?
