### ISSUE TITLE
Bug: Specified as "raspberry 4 upwards" but no armv71 .whl on pypi

### ISSUE THREAD

**Issue by philipp2310** [coqui-ai/STT#1880]
The .whl file DOES exist in the latest pre-release files! So maybe not a real bug anymore, but already fixed?

**Describe the bug**
The documentation talks about the project being runable on raspberry pi 4 or higher, but there is no .whl for ARMv7 at the moment.

**To Reproduce**
1. Run the following command 'pip3 install stt-tflite'
2. Be on a raspi4 while doing step 1
3. See error

**Expected behavior**
stt-tflite should have an arm compatible wheel
(after looking at the supported systems - stt should not have the arm .whl)

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Raspbian GNU/Linux 10 (buster) | 5.10.17-v7l+
- **Python version**: cp37m

**Additional context**
I made a successful switch from deepspeech to coqui with a "manual" setup from: https://github.com/coqui-ai/STT/releases/download/v0.10.0-alpha.6/stt_tflite-0.10.0a6-cp37-cp37m-linux_armv7l.whl - so it is working, just the wheel is mising!
WIP implementation: https://github.com/project-alice-assistant/ProjectAlice/blob/1.0.0-rc1/core/asr/model/CoquiAsr.py

Thank you for making this awesome program publicly available! :)

**Comment by reuben** [comment]
This requires building libstt.so and the Python packages on the official armv7/aarch64 manylinux images. The easiest path would be to follow the approach I used here, and keep everything else as-is, continuing to cross-compile: https://github.com/coqui-ai/STT/pull/1923

We might be able to get away with building directly on emulated armv7/aarch64 for the Python packages only, but libstt.so will be very slow.

**Comment by reuben** [comment]
Closing because we have ARM wheels available.
