### ISSUE TITLE
Feature request: Include compiled generate_scorer_package in official docker image

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#1885]
**Is your feature request related to a problem? Please describe.**
When training a language model in an official docker image obtained via `$ docker pull ghcr.io/coqui-ai/stt-train`, it is possible to train a language model with `generate_lm.py`, but **it is not possible** to generate a scorer package via `./generate_scorer_package`. 

**Describe the solution you'd like**
I'd like a compiled `generate_scorer_package` binary to be included in the docker image.

**Describe alternatives you've considered**
I usually just wget the compiled version from the linux native_clients on github releases

**Additional context**
NA

**Comment by reuben** [comment]
Native client artifacts are already fetched in the training image.
