### ISSUE TITLE
Support Chinese stt?

### ISSUE THREAD

**Issue by jinfagang** [coqui-ai/STT#1896]
Support Chinese stt?

**Comment by JRMeyer** [comment]
Hi there! This repository is actually for `Coqui STT`, are you maybe asking about `Coqui TTS` [here](https://github.com/coqui-ai/tts)?

In either case, can you be more specific about what you mean by "support"? This STT code works out of the box for training a new model with Chinese (simplified or traditional orthographies), and we even have a pre-trained chinese model in the 0.9.3 release.

If your question is really for TTS, you should post a detailed issue there.

**Comment by jinfagang** [comment]
@JRMeyer  OH, not aware that we have also a Coqui TTS as well. So we have a pretrained Chinese model on STT? what about TTS?

**Comment by ananas-hebo** [comment]
https://github.com/coqui-ai/STT/releases

You can download Mandarin Chinese acoustic models, try it.

**Comment by JRMeyer** [comment]
There's a Mandarin Chinese TTS model called `zh-CN/baker/tacotron2-DDC-GST`, but that's in 🐸TTS, not here.

Check out 🐸TTS on github for more info: github.com/coqui-ai/TTS
