### ISSUE TITLE
Feature request: Better handling of OOM from large batch sizes

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#1900]
**Is your feature request related to a problem? Please describe.**

When training an STT model on some data set with some GPU(s), it's impossible to know the largest possible batchsize ahead of time. So, the user must do some search and trial and error to find the largest possible batch size. The trial and error involves setting a batchsize and starting a training run with `--reverse_train --reverse_dev --reverse_test`. If the user hits OOM errors, then they can set a lower batchsize and try again.

This process is sub-optimal for a few reasons:

1. The OOM errors are not obvious. The error usually take the form of: `(1) Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 2048, 2048, 1, 195, 128, 2048] ` (exact values will vary). As such, new users hit this error and don't realize this is an OOM.
2. The error may occur on train and/or dev and/or test, and this takes a long time. The user only knows that train and dev batchsizes are set correctly after a full epoch of both train and dev. The user only knows that the test batchsize is correct at the end of training. However, only the single largest batch of train and dev and test is needed. Only these three batches matter, but currently the user must try all batches in all datasets.
3. Most users are unaware of the flags `--reverse_train --reverse_test --reverse_dev`

**Describe the solution you'd like**
I would like a separate script to quickly find the largest possible batchsize for train and test and dev. Something like `get_batchsize.py`

**Describe alternatives you've considered**
manually sorting data and running a single epoch on a subset of largest samples in train/test/dev 

**Additional context**
This error comes up often on Gitter

**Comment by reuben** [comment]
We've added a new step at the start of training which runs training over the 3 largest batches in the train set, with an explicit message saying if the process crashes it's likely due to memory issues. This should help the problem be detected earlier and should point users in the right direction.
