### ISSUE TITLE
Feature request: Allow random batch order during training

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#1901]
**Is your feature request related to a problem? Please describe.**
you can only train batches in order of length of the batch (i.e. audio length), or reverse audio length

**Describe the solution you'd like**
I'd like to have more control over the order of batches, in particular random ordering

**Comment by ftyers** [comment]
As an addition here, it would be good to be able to order the batches by other metrics, such as perplexity or chars/sec etc.

**Comment by reuben** [comment]
I'm adding shuffling support in #1967. Different (initial and in-batch) ordering is a bit more tricky because the sorting happens at the wrong abstraction level at the moment. @ftyers could you open a separate issue for that?
