### ISSUE TITLE
Bug: Broken link in documentation DATA_FORMATTING.html

### ISSUE THREAD

**Issue by jeremiahrose** [coqui-ai/STT#1932]
In the Coqui STT 0.10.0-alpha.13 documentation, at [https://stt.readthedocs.io/en/latest/playbook/DATA_FORMATTING.html](https://stt.readthedocs.io/en/latest/playbook/DATA_FORMATTING.html), where it says

`Data from Common Voice

If you are using data from Common Voice for training a model, you will need to prepare it as outlined in the 🐸STT documentation.`

The link to https://stt.readthedocs.io/en/latest/TRAINING.html#common-voice-training-data is broken.

**Comment by reuben** [comment]
Thanks for reporting!
