### ISSUE TITLE
Bug: Training Docker image AttributeError: module 'tensorflow' has no attribute 'lite'

### ISSUE THREAD

**Issue by jeremiahrose** [coqui-ai/STT#1937]
**Describe the bug**
When training or converting a model to TFLite with latest Docker image, it fails with the error:

```
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    stt_train.main()
  File "/code/training/coqui_stt_training/train.py", line 1266, in main
    export()
  File "/code/training/coqui_stt_training/train.py", line 1107, in export
    converter = tf.lite.TFLiteConverter(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'lite'
```

**To Reproduce**
I am pulling the Docker image and adding Sox as follows:

```
# Get the latest 🐸STT image
FROM ghcr.io/coqui-ai/stt-train:latest

ENV DEBIAN_FRONTEND=noninteractive

# Install nano editor
RUN apt-get -y update && apt-get install -y nano

# Install sox for inference and for processing Common Voice data
RUN apt-get -y update && apt-get install -y sox
```

Then I am attempting to convert the yesno model checkpoints to TFLite as follows (note - I also got this error with the same Docker image when training a model from scratch)

```
#!/bin/bash
set -x

docker build -t stt-image .

docker run \
    --rm \
    -it \
    --entrypoint /bin/bash \
    --name stt-train \
    --gpus all \
    --mount type=bind,source="$(pwd)"/stt-data,target=/code/stt-data \
    stt-image \
    -c "cd /code && \
        python3 train.py \
          --checkpoint_dir /code/stt-data/checkpoints \
          --export_dir /code/stt-data/exported-model \
          --n_hidden 64 \
          --alphabet_config_path /code/stt-data/alphabet.txt \
          --export_tflite=true "
```

**Expected behavior**
The model should train / convert / export without an error.

**Environment (please complete the following information):**
- Ubuntu 20.04
- Dependency versions as per Docker image `ghcr.io/coqui-ai/stt-train   latest    5adb1e5d8af5`
- CUDA Version: 11.2
- GeForce MX150 2GB

**Additional context**
I believe this is probably an issue with Tensorflow versions, and I am going to try adding `.contrib` to the offending lines in `train.py`

**Comment by jeremiahrose** [comment]
Tensorflow version inside the Docker image is 
```
>>> import tensorflow as tf
2021-08-06 00:37:57.884076: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
>>> print(tf.__version__)
1.15.5
>>> 
```

**Comment by jeremiahrose** [comment]
It appears that TFLite is not available at all in the Docker image.
```
root@bb07cca0b37b:/code# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-08-06 01:36:23.509587: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
>>> tf.lite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'lite'
>>> tf.contrib.lite
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/lazy_loader.py", line 63, in __getattr__
    return getattr(module, item)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 51, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorflow_core.contrib' has no attribute 'lite'
>>> tf.compat.v1.lite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.compat.v1' has no attribute 'lite'
>>> tf.compat.v2.lite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.compat.v2' has no attribute 'lite'
```

**Comment by jeremiahrose** [comment]
Instead of downloading the Docker image I have tried building it from scratch from STT v0.10.0-alpha.13 git repo and I am still getting the above error.

**Comment by jeremiahrose** [comment]
As a workaround, I was able to successfully convert some checkpoints to TFLite with STT v0.10.0-alpha.13 by changing this line in the Dockerfile.train:
`FROM nvcr.io/nvidia/tensorflow:21.05-tf1-py3`
to:
`FROM tensorflow/tensorflow:1.15.5-gpu-py3`
Then rebuilding the Docker image and doing a convert as above.

However, this did not work with training, giving the error:

```
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    stt_train.main()
  File "/code/training/coqui_stt_training/train.py", line 1265, in main
    train()
  File "/code/training/coqui_stt_training/train.py", line 793, in train
    train_loss, _ = run_set("train", epoch, train_init_op)
  File "/code/training/coqui_stt_training/train.py", line 749, in run_set
    feed_dict=feed_dict,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/conv1d (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[tower_0/gradients/tower_0/BiasAdd_4_grad/BiasAddGrad/_75]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/conv1d (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.
```

It seems like the main Coqui branch is relying on a nVidia Docker image that doesn't include TFLite, despite the recent announcement to only support TFLite from now on!

I noticed the update-tf-2.4 branch has switched a lot of the code in train.py to TF 2.4, but this branch is quite old now.

Is there any way I can contribute to help fix this?

**Comment by reuben** [comment]
Ugh, this is really annoying, I have no idea why the NVIDIA image is building TensorFlow with TFLite disabled. The reason why we switched the base image to the NVIDIA one is because it is built against newer CUDA libraries and supports e.g. Ampere cards, whereas the official TensorFlow images don't, as you've seen. I don't see any easy way that keeps everyone happy, unfortunately. I guess the easiest fix is to fork the NVIDIA image and make it build TensorFlow with TFLite enabled. If you feel like that's something you can take a crack at, we can then publish that image on GHCR and use it as the base for the training image.

**Comment by jeremiahrose** [comment]
I'd like to give that a go.

Looking at nvidia's Tensorflow fork on GitHub, it appears that they're using CUDA 10.0 in their [Dockerfiles](https://github.com/NVIDIA/tensorflow/blob/r1.15.5%2Bnv21.05/tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile).

However inside the NVIDIA Docker image I am getting:
```
root@6f654f46ee3a:/workspace# nvcc --version
...
Build cuda_11.3.r11.3/compiler.29745058_0
```

So I guess this is the wrong repo? Do you know where the actual source for the NVIDIA image is?

**Comment by jeremiahrose** [comment]
It seems that nvidia don't publish their Dockerfiles. I've tried recompiling Tensorflow inside nvcr.io/nvidia/tensorflow:21.05-tf1-py3 to add TFLite support, but haven't had much luck yet.

Another solution to this would be simply to have a separate Dockerfile for conversion, e.g:
```
Dockerfile.build
Dockerfile.convert
Dockerfile.train
```
And then adopt a workflow of training to checkpoints with Dockerfile.train, then converting to `.tflite` with Dockerfile.convert.
It isn't pretty but until Coqui supports Tensorflow 2.x I don't see a better solution really.

**Comment by jeremiahrose** [comment]
There is a bug report on nvidia-tensorflow github here: [https://github.com/NVIDIA/tensorflow/issues/16](https://github.com/NVIDIA/tensorflow/issues/16)

Apparently TFLite support was intentionally removed in 2020

**Comment by reuben** [comment]
I've pushed a new training image based on the older NVIDIA base as mentioned on the issue. This means we don't get updates, but until a new GPU architecture comes out this shouldn't be a problem, and by then we won't be on TF1 anymore :)
