### ISSUE TITLE
Bug: intermediateDecode ignores unprocessed internal buffer

### ISSUE THREAD

**Issue by jeremiahrose** [coqui-ai/STT#1953]
**Describe the bug**
Stream.intermediateDecode() ignores part of the buffer data that has been sent to the stream.

**To Reproduce**
(In Python)
```
# 1. Create a stream
model = stt.Model(args.model)
stream_context = model.createStream()

# 2. Feed it a buffer
stream_context.feedAudioContent(some_buffer)

# 3. Do an intermediate decode
text = stream_context.intermediateDecode()
```

**Current behavior**
Depending on the size of some_buffer:
- If some_buffer is smaller than the internal batch size, nothing will be processed.
- If some_buffer is larger than the internal batch size, only the first part will be processed.

**Expected behavior**
All of the audio data that has been sent to the stream API so far would be processed and an intermediate result returned.

This is important when streaming to STT with VAD, where a stream will be automatically stopped whenever VAD detection is negative. If the stream is stopped at a point that is not an exact multiple of the internal batch buffer, parts of the audio will not have been processed by the acoustic model and therefore will be missing from the intermediate result. This causes mis-recognition of words.

Stream.finalizeStream() does not suffer from this defect, but it cannot provide intermediate results because it shuts down the stream completely. Intermediate results are essential for fast / low latency voice recognition.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Custom Yocto Linux
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Coqui Tensorflow
- **TensorFlow version (use command below)**:
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 3.1.0
- **GCC/Compiler version (if compiling from source)**: Yocto cross compiler
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A

**Comment by reuben** [comment]
This is by design. Contributed code examples showed us people were calling intermediateDecode quite liberally and so we made it as fast as possible, only processing already decoded time steps rather than flushing buffers, to avoid performance traps.

**Comment by reuben** [comment]
The idea is that you call intermediateDecode at regular intervals (eg. every 350ms), and call finishStream once you have a longer chunk of silence detected by VAD, starting a new stream after doing that.

**Comment by reuben** [comment]
We could also potentially expand the API so that there's an `intermediateDecodeExpensive` API which is equivalent to finishStream in behavior but does not finalize the Stream instance. In fact if a PR were to show up adding such a modification I would gladly review and accept it :)

**Comment by reuben** [comment]
Closed a bit too early, the PR has now been merged.
