### ISSUE TITLE
Website "Quickstart: Deployment" instructions incorrect

### ISSUE THREAD

**Issue by BitBarrel** [coqui-ai/STT#1962]
Following the Quickstart: Deployment instructions results in an error.

**To Reproduce**
-Install WSL 2 using Debian on Windows.
-Follow the "Quickstart: Deployment" instructions at: https://stt.readthedocs.io/en/latest/
-When executing the last step "# Transcribe an audio file", this error is thrown:

Loading model from file coqui-stt-0.9.3-models.pbmm
TensorFlow: v2.3.0-6-g23ad988fcde
 Coqui STT: v0.10.0-alpha.14-0-g07ed4176
ERROR: Model provided has model identifier 'u/3', should be 'TFL3'

Error at reading model file coqui-stt-0.9.3-models.pbmm
Traceback (most recent call last):
  File "/home/bitbarrel/venv-stt/bin/stt", line 8, in <module>
    sys.exit(main())
  File "/home/bitbarrel/venv-stt/lib/python3.8/site-packages/stt/client.py", line 148, in main
    ds = Model(args.model)
  File "/home/bitbarrel/venv-stt/lib/python3.8/site-packages/stt/__init__.py", line 40, in __init__
    raise RuntimeError(
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)

Edit:
It works when tflite is used instead of pbmm, so it looks like the wrong model was downloaded. How to fix this?

**Comment by reuben** [comment]
Ah, yes, that shouldn't be referencing the pbmm model anymore. Thanks for reporting!

**Comment by reuben** [comment]
Fixed on https://github.com/coqui-ai/STT/commit/b5e8ebb943addc5ee0c0513df368b036279b8657
