### ISSUE TITLE
Missing binaries

### ISSUE THREAD

**Issue by BitBarrel** [coqui-ai/STT#1963]
The binary "generate_scorer_package" is missing.

From the manual here:
https://stt.readthedocs.io/en/latest/LANGUAGE_MODEL.html

> "Finally, we package the trained KenLM model for deployment with generate_scorer_package. You can find pre-built binaries for generate_scorer_package on the official 🐸STT release page (inside native_client.*.tar.xz). "

However, no binaries are available.

**Comment by reuben** [comment]
The binaries are available on the native client archives, as documented: https://github.com/coqui-ai/STT/releases/v0.9.3
