### ISSUE TITLE
Feature request: Make a separate script to create CSV files 

### ISSUE THREAD

**Issue by BitBarrel** [coqui-ai/STT#1974]
Automatically creating test, train, and dev CSV datasets with proper distribution is supported by coqui_stt_training.train using the --auto_input_dataset flag but it would be handy the three CSV files can be generated by a dedicated script. This is because lm_optimizer.py also requires the separate CSV files.

**Comment by reuben** [comment]
You should be able to use `--auto_input_dataset` with lm_optimizer.py as well.

-- reuben

**Comment by BitBarrel** [comment]
It didn't work when I tried that. What is the syntax?
