### ISSUE TITLE
Support OPUS/optional Scorer + package evaluate_tflite.py in training pkg

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#1986]
evaluate_tflite.py 

- Should be included in `coqui_stt_training`?

We've recently moved scripts that used to be called directly `python script.py` to be packaged inside the training package (`training/coqui_stt_training`) and then be called with `python -m coqui_stt_training.script`, for a consistent UI as well as better versioning of the entire code. Eventually one will be able to do all training tasks without cloning the code, just doing a pip install. We should move `evaluate_tflite.py` from the top level to `training/coqui_stt_training`, making any changes needed to handle the new location. For one, the dependency on the `stt` package needs to be made optional and handled with a clean error message instructing users to install the package, as we don't want to add the dependency directly. Then, any CI coverage of `evaluate_tflite.py` needs to be adjusted to call the new location. And finally a forwarding script ala `evaluate.py` in the top level folder can be written to keep the old interface working with a warning message.

- Won't allow eval without a scorer

This should be trivial to fix, just initialize scorer to `None` and only create the `Scorer` instance if a scorer was actually specified in the CLI.

- Doesn't accept opus

Right now `evaluate_tflite.py` is using the `wave` package to decode the input samples. For Opus we'd have to extend that to handle the format, probably with `pyogg`. There's some low level usage of `pyogg` in `training/coqui_stt_training/util/audio.py` which might be a good inspiration, but it might be too low level for `evaluate_tflite.py`, which simply needs the fully decoded file.

**Comment by reuben** [comment]
Fixed by #2049
