### ISSUE TITLE
Bug: ERROR: Could not find a version that satisfies the requirement stt-gpu (from versions: 0.10.0a4)

### ISSUE THREAD

**Issue by nealmcb** [coqui-ai/STT#1994]
**Describe the bug**
Failure to install stt-gpu: "Could not find a version that satisfies the requirement stt-gpu (from versions: 0.10.0a4)"

**To Reproduce**
1. In a fresh venv, run the following command `python -m pip install -U pip && python -m pip install stt-gpu`
2. Observe:

```
Collecting pip
  Using cached pip-21.3-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-21.3
Collecting stt-gpu
  Using cached STT-gpu-0.10.0a4.tar.gz (1.5 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package stt-gpu produced metadata for project name stt. Fix your #egg=stt-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/43/84/e42b1ea7389d33d31e25c6a41439572fddd026a04bd02c4129a22c1ad33e/STT-gpu-0.10.0a4.tar.gz#sha256=1fcd4f925056c6d345a5a577a5821cf44d0120362736e6915ff8837b79a9b129 (from https://pypi.org/simple/stt-gpu/). Requested stt from https://files.pythonhosted.org/packages/43/84/e42b1ea7389d33d31e25c6a41439572fddd026a04bd02c4129a22c1ad33e/STT-gpu-0.10.0a4.tar.gz#sha256=1fcd4f925056c6d345a5a577a5821cf44d0120362736e6915ff8837b79a9b129 has inconsistent name: filename has 'stt-gpu', but metadata has 'stt'
ERROR: Could not find a version that satisfies the requirement stt-gpu (from versions: 0.10.0a4)
ERROR: No matching distribution found for stt-gpu
```

**Expected behavior**
A clean installation of STT for GPU

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: None yet in this venv
- **TensorFlow version (use command below)**: None yet (and no "command below" in this template....)
- **Python version**: 3.8.10
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: system76-cuda-10.0 / system76-cudnn-10.0
- **GPU model and memory**:  NVIDIA GeForce GTX 1650 with 896 CUDA Cores, 16 GB
- **Exact command to reproduce**:

**Additional context**
This is on a System76 Galago pro "galp5" running in "Compute" mode.

Installing stt works fine, displaying:

TensorFlow: v2.3.0-14-g4bdd3955115
 Coqui STT: v1.0.0-0-g27584037

**Comment by reuben** [comment]
The STT-gpu package has been deprecated, we're only shipping the TFLite based `stt` package now. The TFLite backend has a GPU delegate which you can try out by setting the environment variable STT_TFLITE_DELEGATE=gpu while running.
