### ISSUE TITLE
Loosen max numpy version constraint in STT package

### ISSUE THREAD

**Issue by manoranjanb** [coqui-ai/STT#2017]
**Describe the bug**
For python stt 1.0.0 and tts 0.4.1 have conflicting dependencies of numpy

**To Reproduce**
1. Add both stt 1.0.0 and tts 0.4.1 in requirements.txt in python project
2. Run the following command ' pip install -r requirements.txt'
3. See error
The conflict is caused by:
    stt 1.0.0 depends on numpy<=1.17.3 and >=1.17.3
    tts 0.4.1 depends on numpy==1.19.5

**Expected behavior**
stt 1.0.0 and tts 0.4.1 to work seamlessly together 

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS BigSur 2.7 GHz Dual-Core Intel Core i5
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: builds
- **TensorFlow version (use command below)**: tensorboardX-2.4
- **Python version**: 3.8.11
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

**Additional context**
pip version 21.3.1

**Comment by manoranjanb** [comment]
stt works with numpy==1.19.5, please loosen the dependency in stt release

**Comment by reuben** [comment]
> stt works with numpy==1.19.5, please loosen the dependency in stt release

Yeah this is the right fix. In the mean time you can use pip's legacy resolver: `pip --use-deprecated=legacy-resolver install stt==1.0.0 numpy==1.19.5`

**Comment by reuben** [comment]
Fixed on main.
