### ISSUE TITLE
Bug: DLL load failed while importing _impl on win64

### ISSUE THREAD

**Issue by padmalcom** [coqui-ai/STT#2104]
Hi, thanks for your efforts creating coqui ai!
I follow the python example from this link: https://stt.readthedocs.io/en/latest/Python-Examples.html
With the minimal code shown below:
```
from stt import Model, version
if __name__ == '__main__':
	model = Model('sttmodel/model.pbmm')
```

... I run into the following error:

> (coquistt) C:\Users\admin\coquistt>python main.py
> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>     from stt import Model, version
>   File "C:\Users\admin\Anaconda3\envs\coquistt\lib\site-packages\stt\__init__.py", line 23, in <module>
>     from stt.impl import Version as version
>   File "C:\Users\admin\Anaconda3\envs\coquistt\lib\site-packages\stt\impl.py", line 13, in <module>
>     from . import _impl
> ImportError: DLL load failed while importing _impl: Das angegebene Modul wurde nicht gefunden. (Module not found)

I use python 3.8 on a win64 machine.  I have stt 1.2.0 installed.

**Comment by reuben** [comment]
For Anaconda you need to go through their own install channels. We only support official Python and pip.

**Comment by padmalcom** [comment]
Hi @reuben, thank your for your quick reply. I only use conda to manage the environment and pip, to install all my packages. This should work, right?

**Comment by reuben** [comment]
No, conda does their own Python builds with different compilers/options which breaks binary extensions that haven't been built inside the conda system. You need official Python for Windows, or to build STT from source.

**Comment by padmalcom** [comment]
Okay, thanks for the clarification
