### ISSUE TITLE
Question: How to build for windows 

### ISSUE THREAD

**Issue by LambdaMan2K** [coqui-ai/STT#2129]
Hey!  I am trying to build this using rust  and the c wrapper:  https://crates.io/crates/coqui-stt
but I face a link error: LINK : fatal error LNK1181: cannot open input file 'stt.lib'

so what I did was download and extracting the native_client for windows and added the path to the system env paths. 
In that folder I have stt.exe not .lib cuz I am on windows?  the author of the wrapper cant help since he is not using windows. 
can you please guide me in the right direction thank you :)

**Comment by reuben** [comment]
The native client archive also has the necessary libraries: `libstt.so`, `libkenlm.so`, `libstt.so.if.lib` and `libkenlm.so.if.lib`. You should be able to set up your compilation to link against those files, that's what we do to create the `stt.exe` binary, for example. But unfortunately I can't give any specific instructions for the Rust binding as I don't know how Rust handles linking native dependencies in a crossplatform way.

**Comment by LambdaMan2K** [comment]
thank you for your response :) I will look more into it
