### ISSUE TITLE
Bug: web site stt.readthedocs.io doesn't have working info on getting started with training

### ISSUE THREAD

**Issue by FrontierDK** [coqui-ai/STT#2164]
Hi there.

I have just tried a lot of the methods shown on stt.readthedocs.io on how to get started with training...and none of them worked. Will the web site be updated?

**Background**
To make sure I didn't have old stuff, I used a fresh virtual Ubuntu 21.10 desktop, with unddo/snapshots of the VM, so that I could try multiple ways/methods, without having old stuff from previous attempts left over...

https://stt.readthedocs.io/en/latest/TRAINING_INTRO.html
- The build docker from source using Dockerfile.train doesn't work. Throws tons of errors during creation, and can't start.

https://stt.readthedocs.io/en/latest/DEPLOYMENT.html
- Doesn't say how to install prerequisites, when done and running coqui-stt-model-manager install, it throws this error: _legacy-install-failure. Encountered error while trying to install package webrtcvad_

https://www.tensorflow.org/install/source#configure_the_build
- The command _pip install -U --user pip numpy wheel packaging_ fails with "Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.3.4)". Remember, I'm using a fresh/newly installed VM/PC.
The Ubuntu server does get through this, but then we get to the "./configure" command, which tells you to install Baxel. Not told anywhere on the page.

Preparing and training data takes a LOT of time, A lot more trained datasets would be available if the documetation is updated to a level, where you can follow the command guides from a newly installed PC/VM, use just the listed commands...and end out with a working SR PC/VM. A lot of training data might even be shared, so that our models are more versatile. Is there a chance that the documentation is updated?

**Comment by JRMeyer** [comment]
@FrontierDK is this the error you get with building the dockerfile? https://github.com/coqui-ai/STT/issues/2168

FWIW -- the best way to start training is to pull down the pre-built docker images:

```
$ docker pull ghcr.io/coqui-ai/stt-train
```

this is actually the recommended training setup, [as noted in the docs](https://stt.readthedocs.io/en/latest/TRAINING_INTRO.html#dockerfile-setup)... did this not work for you for some reason?
