### ISSUE TITLE
Upgrade training image to Python 3.7

### ISSUE THREAD

**Issue by reuben** [coqui-ai/STT#2172]
Python 3.6 is EOL, dependencies are starting to release versions that don't support it. We should bump to 3.7 on the training image.

**Comment by wasertech** [comment]
I think we can close this issue.

**Comment by wasertech** [comment]
Do with commit https://github.com/coqui-ai/STT/commit/f8410dc74272860cb7e8c2ed242d9939e3f0c5e9
