### ISSUE TITLE
Bug: lm_optimize fails due to check failing.

### ISSUE THREAD

**Issue by BjornTheProgrammer** [coqui-ai/STT#2302]
Welcome to the 🐸STT project! We are excited to see your interest, and appreciate your support!

This repository is governed by the Contributor Covenant Code of Conduct. For more details, see the [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md) file.

If you've found a bug, please provide the following information:

**Describe the bug**
When attempting to run the optimizer python script to determine the best alpha and beta for a customer scorer, it errors with the following output on an M1 Macbook 2020 running macOS Monterey 12.5.1.

```
python3 lm_optimizer.py
2022-09-30 12:37:43.198725: F tensorflow/core/lib/monitoring/sampler.cc:42] Check failed: bucket_limits_[i] > bucket_limits_[i - 1] (0 vs. 10)
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

**To Reproduce**
1. Run `docker pull ghcr.io/coqui-ai/stt-train:v0.10.0-alpha.4`
2. Run `docker run  -it --name stt-test --entrypoint /bin/bash ghcr.io/coqui-ai/stt-train:v0.10.0-alpha.4`
3.  Make file at /code/data/text.txt with following data
```
up
down
left
right
velocity
distance
forward
backward
faster
slower
stop
start
take off
land
launch
```
5. Run `python3 generate_lm.py --input_txt /code/data/text.txt --output_dir /code/data/ --top_k 500000 --kenlm_bins /code/kenlm/build/bin/ --arpa_order 5 --max_arpa_memory "85%" --arpa_prune "0|0|1" --binary_a_bits 255 --binary_q_bits 8 --binary_type trie --discount_fallback`
6. Run `python3 lm_optimizer.py`
7. See error

**Expected behavior**
To receive an optimized alpha and beta

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
	macOS Monterey 12.5.1

- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
	Whatever build that is within the docker

- **TensorFlow version (use command below)**:
	Whatever that is within the docker

- **Python version**:
	Whatever that is within the docker

- **Bazel version (if compiling from source)**:
	Whatever that is within the docker

- **GCC/Compiler version (if compiling from source)**:
	Whatever that is within the docker

- **CUDA/cuDNN version**:
	Whatever that is within the docker

- **GPU model and memory**:
	No GPU being utilized

- **Exact command to reproduce**:

**Additional context**

**Comment by wasertech** [comment]
Why are your using `v0.10.0-alpha.4` ? Try with the latest `1.4.0` if it’s still doesn’t work,  it’s because your are using an M1 Mac. Which as far as I know is not support yet.

**Comment by BjornTheProgrammer** [comment]
Thank you, I was using an M1 MacBook, and I apologize for wasting your time, I attempted many fixes not stated here to solve the import error and apparently fixed them, but couldn't get the final TensorFlow issue to work. So I have given up on utilizing the lm_optomizer on my Mac. Thanks again for your help.
